panaderia_mana/panaderia_mana/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from insumo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insumos/', include('insumo.urls')),
    path('', views.pagina_inicio, name='pagina_inicio'),  # Ruta para la página de inicio
    #path('', TemplateView.as_view(template_name='base/home.html'), name='home'),
    #path('', include('apps.usuario.urls', namespace='usuario')),
    #path('productos/', include('producto.urls')),
    path('empleado/', include('empleado.urls')),
    #path('cliente/', include('cliente.urls')),
    path('usuario/', include('apps.usuario.urls')),
    #path('pedidos/', include('pedido.urls')),
    #path('pedido/', include('pedido.urls', namespace='pedido')),
    #path('pedido/', include('pedido.urls')),
    path('pedido/', include('pedido.urls', namespace='pedido')),
    path('proveedor/', include('proveedor.urls')),





                  # path('', views.index, name='index'),  # Ruta para la página de inicio
    # path('registro-pedidos/', views.registro_pedidos, name='registro_pedidos'),  # Ruta para Registro de Pedidos
    #path('gestion-producto/', views.gestion_producto, name='gestion_producto'),  # Ruta para Gestión de Productos
    path('venta/', include('venta.urls')), # Ruta para Ventas

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panaderia_mana/pedido/urls.py
"""

# pedido/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('crear/', views.crear_pedido, name='crear_pedido'),
    path('<int:pedido_id>/agregar-items/', views.agregar_items_pedido, name='agregar_items_pedido'),
]
"""

# urls.py
from django.urls import path
from .views import registrar_pedido
from . import views
app_name = 'pedido'
urlpatterns = [
    path('registrar-pedido/', views.registrar_pedido, name='registrar_pedido'),
    path('', views.listar_pedidos, name='listar_pedidos'),
    path('pedido/<int:pedido_id>/', views.detalles_pedido, name='detalles_pedido'),
    path('<int:pedido_id>/eliminar/', views.eliminar_pedido, name='eliminar_pedido'),
    path('<int:pedido_id>/editar/', views.editar_pedido, name='editar_pedido'),


    path('insumos-mas-pedidos/pdf/', views.insumos_mas_pedidos_pdf, name='insumos_mas_pedidos_pdf'),

    path('lista-reportes/', views.lista_reportes, name='lista_reportes'),


    path('recibir/<int:pedido_id>/', views.recibir_pedido, name='recibir_pedido'),
]

panaderia_mana/venta/urls.py
from django.urls import path
from venta import views


urlpatterns = [
    path('lista_productos', views.lista_productos, name='lista_productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('editar_producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('eliminar_producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('productos/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),

    path('lista_clientes', views.listar_clientes, name='listar_clientes'),
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('editar_cliente/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar_cliente/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('lista_ventas', views.lista_ventas, name='lista_ventas'),
    path('registrar_venta', views.registrar_venta, name='registrar_venta'),
    path('eliminar_venta/<int:venta_id>/', views.eliminar_venta, name='eliminar_venta'),
    #path('nueva_venta', views.AgregarItem.as_view(), name='nueva_venta'),


    path('informe-ventas/pdf/', views.informe_ventas_pdf, name='informe_ventas_pdf'),
    path('productos-mas-vendidos/pdf/', views.productos_mas_vendidos_pdf, name='productos_mas_vendidos_pdf'),
    path('empleados-mas-ventas/pdf/', views.empleados_mas_ventas_pdf, name='empleados_mas_ventas_pdf'),
    path('informe-ventas-diarias/pdf', views.ventas_diarias_pdf, name='informe_ventas_diarias'),

]

panaderia_mana/pedido/models.py
# pedido/models.py
from django.db import models
from insumo.models import Insumo
from proveedor.models import Proveedor
from django.db.models import Sum



"""
class Pedido(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, related_name='pedidos')
    fecha_emision = models.DateTimeField(auto_now_add=True)
    fechaRecepcion = models.DateField()
    numero_pedido = models.IntegerField()
    
    monto_total = models.FloatField(default=0.0)

    def __str__(self):
        return f"Pedido {self.numero_pedido} - {self.proveedor.nombre}"

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, related_name='items', on_delete=models.CASCADE)
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.FloatField()

    def __str__(self):
        return f"{self.insumo.nombre} - {self.cantidad} unidades"

"""

"""
class Insumo(models.Model):
    nombre = models.CharField(max_length=100)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nombre
"""

class Pedido(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, default=1)
    fecha_solicitud = models.DateField()
    observaciones = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Pedido {self.numero_pedido} - {self.proveedor.nombreCompleto}'


    # Método para calcular el total del pedido
    def total(self):
        return self.detalles.aggregate(total=Sum('precio_total'))['total'] or 0

class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='detalles')
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.cantidad} de {self.insumo.nombre}'




##############RECEPCION PEDIDO#####################


#from django.contrib.auth.models import User
#from panaderia_mana.empleado.admin import Empleado
from empleado.models import Empleado


class RecepcionPedido(models.Model):
    pedido = models.OneToOneField(Pedido, on_delete=models.CASCADE, related_name='recepcion')
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, default=1)
    fecha_recepcion = models.DateField(auto_now_add=True)
    observaciones = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Recepción de Pedido {self.pedido.numero_pedido}'

panaderia_mana/pedido/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Pedido, DetallePedido, Insumo
from .forms import PedidoForm

from django.shortcuts import redirect
from django.contrib import messages
from .forms import PedidoForm, DetallePedidoFormSet

@login_required(login_url='usuario:login')
def listar_pedidos(request):
    # Obtener todos los pedidos
    pedidos = Pedido.objects.all()
    context = {
        'pedidos': pedidos
    }
    return render(request, 'pedido/listar_pedidos.html', context)

@login_required(login_url='usuario:login')
def registrar_pedido(request):
    if request.method == 'POST':
        pedido_form = PedidoForm(request.POST)

        if pedido_form.is_valid():
            pedido = pedido_form.save()
            # Procesar los detalles del pedido
            insumo_ids = request.POST.getlist('insumo_id[]')
            cantidades = request.POST.getlist('cantidad[]')

            for insumo_id, cantidad in zip(insumo_ids, cantidades):
                insumo = Insumo.objects.get(id=insumo_id)
                DetallePedido.objects.create(
                    pedido=pedido,
                    insumo=insumo,
                    cantidad=cantidad,
                    precio_total=insumo.precio_unitario * int(cantidad)
                )
            #return redirect('pedido_exitoso')
            return redirect('pedido:listar_pedidos')
    else:
        pedido_form = PedidoForm()
    insumos = Insumo.objects.all()
    context = {
        'pedido_form': pedido_form,
        'insumos': insumos,
    }
    #return render(request, 'registrar_pedido.html', context)
    return render(request, 'pedido/registrar_pedido.html', context)

@login_required(login_url='usuario:login')
def detalles_pedido(request, pedido_id):
    # Obtener el pedido por su ID
    pedido = get_object_or_404(Pedido, id=pedido_id)
    # Obtener los detalles asociados al pedido
    detalles = DetallePedido.objects.filter(pedido=pedido)
    context = {
        'pedido': pedido,
        'detalles': detalles
    }
    return render(request, 'pedido/detalles_pedido.html', context)

"""
def detalles_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id)
    return render(request, 'pedido/detalles_pedido.html', {'pedido': pedido})
"""
@login_required(login_url='usuario:login')
def eliminar_pedido(request, pedido_id):
    # Obtener el pedido por su ID y eliminarlo
    pedido = get_object_or_404(Pedido, id=pedido_id)
    pedido.delete()
    messages.success(request, 'Pedido eliminado correctamente.')
    # Redirigir a la lista de pedidos
    return redirect('pedido:listar_pedidos')


"""def editar_pedido(request, pedido_id):
    # Obtener el pedido y sus detalles
    pedido = get_object_or_404(Pedido, id=pedido_id)
    detalles = DetallePedido.objects.filter(pedido=pedido)

    if request.method == 'POST':
        pedido_form = PedidoForm(request.POST, instance=pedido)
        detalle_formset = DetallePedidoFormSet(request.POST, queryset=detalles)

        if pedido_form.is_valid() and detalle_formset.is_valid():
            pedido_form.save()
            detalle_formset.save()
            messages.success(request, 'Pedido actualizado correctamente.')
            return redirect('pedido/listar_pedidos.html')
    else:
        pedido_form = PedidoForm(instance=pedido)
        detalle_formset = DetallePedidoFormSet(queryset=detalles)

    context = {
        'pedido_form': pedido_form,
        'detalle_formset': detalle_formset,
        'pedido': pedido
    }
    return render(request, 'pedido/editar_pedido.html', context)"""

@login_required(login_url='usuario:login')
def editar_pedido(request, pedido_id):
    # Obtener el pedido y sus detalles
    pedido = get_object_or_404(Pedido, id=pedido_id)
    detalles = DetallePedido.objects.filter(pedido=pedido)

    if request.method == 'POST':
        pedido_form = PedidoForm(request.POST, instance=pedido)

        if pedido_form.is_valid():
            pedido = pedido_form.save()

            # Eliminar detalles previos para reemplazarlos con los nuevos
            detalles.delete()

            # Procesar los nuevos detalles del pedido
            insumo_ids = request.POST.getlist('insumo_id[]')
            cantidades = request.POST.getlist('cantidad[]')

            for insumo_id, cantidad in zip(insumo_ids, cantidades):
                insumo = Insumo.objects.get(id=insumo_id)
                DetallePedido.objects.create(
                    pedido=pedido,
                    insumo=insumo,
                    cantidad=cantidad,
                    precio_total=insumo.precio_unitario * int(cantidad)
                )

            messages.success(request, 'Pedido actualizado correctamente.')
            return redirect('pedido:listar_pedidos')
    else:
        pedido_form = PedidoForm(instance=pedido)

    insumos = Insumo.objects.all()
    context = {
        'pedido_form': pedido_form,
        'detalles': detalles,
        'pedido': pedido,
        'insumos': insumos,
    }
    return render(request, 'pedido/editar_pedido.html', context)



#reportes

@login_required(login_url='usuario:login')
def lista_reportes(request):
    return render(request, 'pedido/lista_reportes.html')


#1. Vista para Insumos Más Pedidos en PDF

from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Sum
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from .models import DetallePedido

@login_required(login_url='usuario:login')
def insumos_mas_pedidos_pdf(request):

    # Configurar la respuesta para ver el PDF en el navegador
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="insumos_mas_pedidos.pdf"'  # 'inline' para mostrar primero y luego recien descargarlo

    # Crear el archivo PDF
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    p.setTitle("Informe de Insumos Más Pedidos")

    # Título del documento
    p.drawString(100, 800, "Panadería El Maná")
    p.drawString(100, 780, "Informe de Insumos Más Pedidos")

    # Encabezados de la tabla
    p.drawString(100, 750, "Nombre del Insumo")
    p.drawString(300, 750, "Total Pedido")

    # Consultamos los insumos más pedidos
    insumos_mas_pedidos = (DetallePedido.objects
                           .values('insumo__nombre')
                           .annotate(total_pedido=Sum('cantidad'))
                           .order_by('-total_pedido'))

    # Agregar datos a la tabla
    y = 730  # Coordenada vertical inicial para los datos
    for insumo in insumos_mas_pedidos:
        p.drawString(100, y, insumo['insumo__nombre'])
        p.drawString(300, y, str(insumo['total_pedido']))
        y -= 20

    # Finalizar y guardar el PDF
    p.showPage()
    p.save()

    # Obtener contenido del PDF y escribirlo en la respuesta
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response


#                       RECEPCION PEDIDO


from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Pedido, RecepcionPedido, Insumo
from .forms import RecepcionPedidoForm  # Crear un formulario para la recepción

from empleado.models import Empleado
@login_required
def recibir_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id)

    # Verificar si el pedido ya fue recibido
    if hasattr(pedido, 'recepcion'):
        # Redirigir si ya se ha recibido este pedido
        #return redirect('pedido:detalle_pedido', pedido_id=pedido.id)
        return redirect('pedido:listar_pedidos')



    if request.method == 'POST':
        recepcion_form = RecepcionPedidoForm(request.POST)

        if recepcion_form.is_valid():
            recepcion = recepcion_form.save(commit=False)
            recepcion.pedido = pedido
            recepcion.empleado = Empleado.objects.get(usuario=request.user)
            recepcion.fecha_recepcion = timezone.now()
            recepcion.save()

            # Actualizar el stock de cada insumo utilizando el método aumentar_stock
            for detalle in pedido.detalles.all():
                detalle.insumo.aumentar_stock(detalle.cantidad)

            #return redirect('pedido:detalle_pedido', pedido_id=pedido.id) no me estaria funcioanndo esta url
            return redirect('pedido:listar_pedidos')
    else:
        recepcion_form = RecepcionPedidoForm()

    context = {
        'pedido': pedido,
        'detalles': pedido.detalles.all(),
        'recepcion_form': recepcion_form,
    }
    return render(request, 'pedido/recibir_pedido.html', context)

panaderia_mana/templates/pedido/agregar_items_pedido.html
<!-- pedido/templates/pedido/agregar_items_pedido.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Insumos al Pedido</title>
    <!-- Incluimos el CSS de Bootstrap o Tailwind -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="container mt-5">
        <h1>Agregar Insumos al Pedido {{ pedido.numero_pedido }}</h1>
        <h3>Proveedor: {{ pedido.proveedor.nombre }}</h3>
        <form method="POST" id="item-form" action="{% url 'agregar_items_pedido' pedido.id %}">
            {% csrf_token %}
            <!-- Formulario para seleccionar el insumo y la cantidad -->
            <div class="mb-3">
                <label for="id_insumo" class="form-label">Insumo:</label>
                {{ item_form.insumo|as_widget(attrs={'class': 'form-control'}) }}
            </div>
            <div class="mb-3">
                <label for="id_cantidad" class="form-label">Cantidad:</label>
                {{ item_form.cantidad|as_widget(attrs={'class': 'form-control'}) }}
            </div>
            <div class="mb-3">
                <label for="id_precio" class="form-label">Precio:</label>
                {{ item_form.precio|as_widget(attrs={'class': 'form-control'}) }}
            </div>
            <button type="submit" class="btn btn-primary">Agregar Insumo</button>
        </form>

        <!-- Tabla para mostrar los insumos agregados al pedido -->
        <h2 class="mt-5">Insumos Agregados</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Insumo</th>
                    <th>Cantidad</th>
                    <th>Precio Unitario</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <td>{{ item.insumo.nombre }}</td>
                    <td>{{ item.cantidad }}</td>
                    <td>{{ item.precio }}</td>
                    <td>{{ item.cantidad|floatformat:2 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        // Aquí podrías agregar la lógica para enviar el formulario usando AJAX y actualizar la tabla sin recargar la página.
        // Ejemplo de cómo capturar el envío del formulario y actualizar la tabla.
        $('#item-form').submit(function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(response) {
                    // Aquí se puede actualizar la tabla de insumos sin recargar la página
                    location.reload();  // Recargar la página para ver los nuevos insumos agregados
                }
            });
        });
    </script>
</body>
</html>

panaderia_mana/templates/pedido/crear_pedido.html
<!-- templates/pedido/crear_pedido.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Pedido</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <h2 class="my-4">Crear Pedido</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ pedido_form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Crear Pedido</button>
        </form>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

panaderia_mana/templates/pedido/detalles_pedido.html
{% extends 'base.html' %}

{% block title %}
    Detalles del Pedido
{% endblock %}

{% block titulo %}
    Detalles del Pedido N°{{ pedido.id }}
{% endblock %}

{% block content %}

    <p><strong>Proveedor:</strong> {{ pedido.proveedor }}</p>
    <p><strong>Fecha:</strong> {{ pedido.fecha_solicitud }}</p>
    <p><strong>Observaciones:</strong> {{ pedido.observaciones }}</p> <br>

    <h2>Insumos del Pedido</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Insumo</th>
                <th>Cantidad</th>
                <th>Precio Unitario</th>
                <th>Precio Total</th>
            </tr>
        </thead>
        <tbody>
            {% for detalle in detalles %}
            <tr>
                <td>{{ detalle.insumo.nombre }}</td>
                <td>{{ detalle.cantidad }}</td>
                <td>{{ detalle.insumo.precio_unitario }}</td>
                <td>{{ detalle.precio_total }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p><strong>Total:</strong> {{ pedido.total }}</p>

    <!-- Funcionalidad solo para usuario registrado -->
    <div class="container mt-5 text-center">
        <a href="/pedido/" class="btn btn-primary">Regresar</a>
        <a href="/pedido/{{ pedido.id }}/editar" class="btn bg-faded">Editar</a>
        <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmarEliminacionModal">Eliminar</a>

        <!-- Enlace para recibir el pedido solo si aún no se ha recibido -->
        {% if not pedido.recepcion %}
            <a href="{% url 'pedido:recibir_pedido' pedido.id %}" class="btn btn-success">Recibir Pedido</a>
        {% else %}
        <p class="text-end"><strong>Pedido recibido el:</strong> {{ pedido.recepcion.fecha_recepcion }}</p>
        <p class="text-end"><strong>Por el empleado: </strong>{{ pedido.recepcion.empleado.nombreCompleto |upper}}</p>
        {% endif %}
    </div>

    <!-- Modal de Confirmación de Eliminación -->
    <div class="modal fade" id="confirmarEliminacionModal" tabindex="-1" aria-labelledby="confirmarEliminacionModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmarEliminacionModalLabel">Confirmar Eliminación</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                    ¿Estás seguro de que deseas eliminar este pedido? Esta acción no se puede deshacer.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <a href="{% url 'pedido:eliminar_pedido' pedido.id %}" class="btn btn-danger">Eliminar</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

panaderia_mana/templates/pedido/listar_pedidos.html
{% extends 'base.html' %}

{% block title %}
    Lista de Pedidos
{% endblock %}

{% block titulo %}
    Lista de Pedidos
{% endblock %}

{% block content %}
<br>
{% if messages %}
    <div class="alert alert-success mt-3">
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
<br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID del Pedido</th>
                <th>Fecha</th>
                <th>Total</th>
                <th>Proveedor</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido in pedidos %}
            <tr>
                <td>{{ pedido.id }}</td>
                <td>{{ pedido.fecha_solicitud }}</td>
                <td>{{ pedido.total }}</td>
                <td>{{ pedido.proveedor}}</td>
                <td>
     <!--aca quiero un link que me lleve a la descripcion de cada pedido, es decir detalle pedido-->
                <!-- Botón para ver detalles -->
                <a href="/pedido/pedido/{{ pedido.id }}/" class="btn btn-primary">Ver detalles</a> -
                <a href="/pedido/{{ pedido.id }}/editar" class="btn bg-faded">Editar</a> -
              <!--    <a href="{% url 'pedido:detalles_pedido' pedido.id %}" class="btn btn-info">Ver detalles</a>
                <a class="btn bg-danger" href="{% url 'pedido:eliminar_pedido' pedido.id %}">Eliminar</a></td>
                <a href="{% url 'pedido:eliminar_pedido' pedido_id=pedido.id %}" class="btn btn-danger" onclick="return confirmarEliminacion()">Eliminar</a>-->
                <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmarEliminacionModal" data-id="{{ pedido.id }}">Eliminar</a>
                </td>
            </tr>

            <!-- Modal de confirmación -->
            <div class="modal fade" id="confirmarEliminacionModal" tabindex="-1" aria-labelledby="confirmarEliminacionModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmarEliminacionModalLabel">Confirmación de Eliminación</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            ¿Estás seguro de que deseas eliminar este pedido? Esta acción no se puede deshacer.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <a id="confirmarEliminacionBtn" href="#" class="btn btn-danger">Eliminar</a>
                        </div>
                    </div>
                </div>
            </div>



            {% endfor %}
        </tbody>
    </table>
<a class="btn bg-primary" href="{% url 'pedido:registrar_pedido' %}">Registar un Pedido</a>
{% endblock %}
{% block funcionesjs %}
    <script>
        function confirmarEliminacion() {
            return confirm("¿Estás seguro de que deseas eliminar este pedido?");
        }
    </script>
    <script>
        // Detectar cuando se abre el modal y establecer el enlace
        var modal = document.getElementById('confirmarEliminacionModal');
        modal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget;  // Botón que activó el modal
            var pedidoId = button.getAttribute('data-id');  // Obtener el ID del pedido

            // Actualizar el enlace en el botón de confirmación
            var eliminarBtn = document.getElementById('confirmarEliminacionBtn');
            eliminarBtn.href = `/pedido/${pedidoId}/eliminar/`;
        });
    </script>
{% endblock %}