panaderia_mana/apps/usuario/urls.py
from django.urls import path
from apps.usuario import views

app_name = 'usuario'
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path('listar/', views.listar_usuarios, name='listar_usuarios'),
    #path('crear/', views.crear_usuario, name='crear_usuario'),
    #path('editar/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    #path('eliminar/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
 ]

panaderia_mana/panaderia_mana/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from insumo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insumos/', include('insumo.urls')),
    path('', views.pagina_inicio, name='pagina_inicio'),  # Ruta para la página de inicio
    #path('', TemplateView.as_view(template_name='base/home.html'), name='home'),
    #path('', include('apps.usuario.urls', namespace='usuario')),
    #path('productos/', include('producto.urls')),
    path('empleado/', include('empleado.urls')),
    #path('cliente/', include('cliente.urls')),
    path('usuario/', include('apps.usuario.urls')),
    #path('pedidos/', include('pedido.urls')),
    #path('pedido/', include('pedido.urls', namespace='pedido')),
    #path('pedido/', include('pedido.urls')),
    path('pedido/', include('pedido.urls', namespace='pedido')),
    path('proveedor/', include('proveedor.urls')),





                  # path('', views.index, name='index'),  # Ruta para la página de inicio
    # path('registro-pedidos/', views.registro_pedidos, name='registro_pedidos'),  # Ruta para Registro de Pedidos
    #path('gestion-producto/', views.gestion_producto, name='gestion_producto'),  # Ruta para Gestión de Productos
    path('venta/', include('venta.urls')), # Ruta para Ventas

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panaderia_mana/pedido/urls.py
"""

# pedido/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('crear/', views.crear_pedido, name='crear_pedido'),
    path('<int:pedido_id>/agregar-items/', views.agregar_items_pedido, name='agregar_items_pedido'),
]
"""

# urls.py
from django.urls import path
from .views import registrar_pedido
from . import views
app_name = 'pedido'
urlpatterns = [
    path('registrar-pedido/', views.registrar_pedido, name='registrar_pedido'),
    path('', views.listar_pedidos, name='listar_pedidos'),
    path('pedido/<int:pedido_id>/', views.detalles_pedido, name='detalles_pedido'),
    path('<int:pedido_id>/eliminar/', views.eliminar_pedido, name='eliminar_pedido'),
    path('<int:pedido_id>/editar/', views.editar_pedido, name='editar_pedido'),


    path('insumos-mas-pedidos/pdf/', views.insumos_mas_pedidos_pdf, name='insumos_mas_pedidos_pdf'),

    path('lista-reportes/', views.lista_reportes, name='lista_reportes'),


    path('recibir/<int:pedido_id>/', views.recibir_pedido, name='recibir_pedido'),
]

panaderia_mana/venta/urls.py
from django.urls import path
from venta import views


urlpatterns = [
    path('lista_productos', views.lista_productos, name='lista_productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('editar_producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('eliminar_producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('productos/<int:producto_id>/', views.detalle_producto, name='detalle_producto'),

    path('lista_clientes', views.listar_clientes, name='listar_clientes'),
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('editar_cliente/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar_cliente/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('lista_ventas', views.lista_ventas, name='lista_ventas'),
    path('registrar_venta', views.registrar_venta, name='registrar_venta'),
    path('eliminar_venta/<int:venta_id>/', views.eliminar_venta, name='eliminar_venta'),
    #path('nueva_venta', views.AgregarItem.as_view(), name='nueva_venta'),


    path('informe-ventas/pdf/', views.informe_ventas_pdf, name='informe_ventas_pdf'),
    path('productos-mas-vendidos/pdf/', views.productos_mas_vendidos_pdf, name='productos_mas_vendidos_pdf'),
    path('empleados-mas-ventas/pdf/', views.empleados_mas_ventas_pdf, name='empleados_mas_ventas_pdf'),
    path('informe-ventas-diarias/pdf', views.ventas_diarias_pdf, name='informe_ventas_diarias'),

]

panaderia_mana/templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{% block title %}Mi Sitio{% endblock %}</title>
            <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
                <!-- Google fonts-->
                <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
                <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

                <style>
                    .link-image {
                        transition: transform 0.3s;
                    }
                    .link-image:hover {
                        transform: scale(1.05);
                    }
                </style>

            <link rel="stylesheet" href="{% static 'css/estilos.css' %}" >
            <link rel="stylesheet" href="{% static 'css/styles.css' %}">

        </head>
        <body>
            <!-- Header común -->
             <header>
                <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">Panadería</span>
                <span class="site-heading-lower">El Maná</span>
                </h1>
             </header>
        <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
                <div class="container">
                    <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="">Panadería El Maná</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mx-auto">

                            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="/">INICIO</a></li>
                            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'lista_insumos' %}">Gestión de Insumos</a></li>
                            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'lista_productos' %}">Gestión de Productos</a></li>
                             {% if user.is_authenticated %}
                                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'pedido:lista_reportes' %}">Gestión de REPORTES</a></li>
                            {% endif %}
                            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'lista_ventas' %}">Ventas</a></li>
                        </ul>
                        <span class="navbar-text ms-auto">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                                <a class="btn btn-outline-success me-2"
                                href="{% url 'usuario:logout' %}">Cerrar sesión</a>
                            {% else %}
                                <a class="btn btn-outline-success me-2"
                                href="{% url 'usuario:login' %}">Iniciar sesión</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </nav>
            <!-- Contenido principal -->
            <section class="page-section container cta">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-9 mx-auto">
                            <div class="cta-inner bg-faded text-center rounded">
                                <h2 class="section-heading mb-4">
                                    <span class="section-heading-upper">{% block titulo %}{% endblock %}</span>
                                    <span class="section-heading-lower">El Maná</span>
                                </h2>
                            </div>
                            {% block content %}{% endblock %}
                        </div>
                    </div>
                </div>
            </section>
            <main>
                <!-- Modal de Confirmación para Eliminar Insumo -->
                <div class="modal fade" id="eliminarModal" tabindex="-1" aria-labelledby="eliminarModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="eliminarModalLabel">Confirmar Eliminación</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                            </div>
                            <div class="modal-body">
                                ¿Estás seguro de que deseas eliminar este insumo del pedido?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <button type="button" class="btn btn-danger" id="confirmarEliminar">Eliminar</button>
                            </div>
                        </div>
                    </div>
                </div>

            </main>

            <!-- Footer común -->
            <footer class="marron text-white py-4 text-center fixed bottom-0 w-full">
                <div class="mx-auto flex flex-col lg:flex-row justify-between lg:justify-center items-center">
                    <div class="flex flex-wrap space-x-4 lg:space-x-8 xl:space-x-12 2xl:space-x-16">
                        <a href="https://www.facebook.com" class="flex items-center space-x-2 group text-white no-underline">
                            <i class="fab fa-facebook-f text-xl md:text-2xl group-hover:text-blue-500"></i>
                            <span class="hidden md:inline-block group-hover:text-blue-500">Facebook</span>
                        </a>
                        <a href="https://www.instagram.com" class="flex items-center space-x-2 group text-white no-underline">
                            <i class="fab fa-instagram text-xl md:text-2xl group-hover:text-pink-500"></i>
                            <span class="hidden md:inline-block group-hover:text-pink-500">Instagram</span>
                        </a>
                        <a href="https://tiktok.com" class="flex items-center space-x-2 group text-white no-underline">
                            <i class="fab fa-tiktok text-xl md:text-2xl group-hover:text-black"></i>
                            <span class="hidden md:inline-block group-hover:text-black">TikTok</span>
                        </a>
                        <a href="https://twitter.com" class="flex items-center space-x-2 group text-white no-underline">
                            <i class="fab fa-twitter text-xl md:text-2xl group-hover:text-blue-400"></i>
                            <span class="hidden md:inline-block group-hover:text-blue-400">Twitter</span>
                        </a>
                        <a href="mailto:youremail@gmail.com" class="flex items-center space-x-2 group text-white no-underline">
                            <i class="fas fa-envelope text-xl md:text-2xl group-hover:text-red-500"></i>
                            <span class="hidden md:inline-block group-hover:text-red-500">Gmail</span>
                        </a>
                    </div>
                </div>
            </footer>

            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
            <script src="{% static 'js/scripts.js' %} "></script>

            {% block funcionesjs %}{% endblock %}
            </body>
    </html>

panaderia_mana/templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>El Maná - Panadería</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


<!-- cuando estaba en css, el de abajo esta en static/css
      <link rel="stylesheet" href="{% static 'estilos.css' %}">
      <link rel="stylesheet" href="{% static 'styles.css' %}">
-->
        <link rel="stylesheet" href="{% static 'css/estilos.css' %}" >
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    </head>
    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">Panadería</span>
                <span class="site-heading-lower">El Maná</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="">Panadería El Maná</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">

                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="">INICIO</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'lista_insumos' %}">Gestión de Insumos</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="venta/lista_productos">Gestión de Productos</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="venta/lista_ventas">Ventas</a></li>
                    </ul>
                    <span class="navbar-text ms-auto">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                                <a class="btn btn-outline-success me-2"
                                href="{% url 'usuario:logout' %}">Cerrar sesión</a>
                            {% else %}
                                <a class="btn btn-outline-success me-2"
                                href="{% url 'usuario:login' %}">Iniciar sesión</a>
                            {% endif %}
                        </span>
                </div>
            </div>
        </nav>
        <section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <!--<img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="assets/img/intro2.jpg" alt="..." /> -->
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'img/intro2.jpg' %}" alt="..."/>
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Productos del Día</span>
                            <span class="section-heading-lower">¡Recien Horneados!</span>
                        </h2>
                        <p class="mb-3">Panadería el Maná es un rincón acogedor donde el aroma a pan recién horneado te da la bienvenida desde el primer momento. Aquí, cada pieza es elaborada con amor y dedicación, utilizando recetas artesanales que han pasado de generación en generación.</p>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="#!">¡Mira Nuestra Variedad!</a></div>
                    </div>
                </div>
            </div>
        </section>
        <section class="page-section cta">
            <div class="container">
                <div class="row">
                    <div class="col-xl-9 mx-auto">
                        <div class="cta-inner bg-faded text-center rounded">
                            <h2 class="section-heading mb-4">
                                <span class="section-heading-upper">Lo que Ofrecemos</span>
                                <span class="section-heading-lower">Para Ti</span>
                            </h2>
                            <p class="mb-0">Desde croissants dorados hasta panes integrales llenos de sabor, en Maná encontrarás una variedad irresistible que deleitará tus sentidos. Ya sea para un desayuno especial o para acompañar tus comidas diarias, la frescura y la calidad están garantizadas en cada bocado. ¡Ven y descubre el sabor de la tradición!</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <footer class="marron text-white py-4 text-center fixed bottom-0 w-full">
            <div class="mx-auto flex flex-col lg:flex-row justify-between lg:justify-center items-center">
                <div class="flex flex-wrap space-x-4 lg:space-x-8 xl:space-x-12 2xl:space-x-16">
                    <a href="https://www.facebook.com" class="flex items-center space-x-2 group text-white no-underline">
                        <i class="fab fa-facebook-f text-xl md:text-2xl group-hover:text-blue-500"></i>
                        <span class="hidden md:inline-block group-hover:text-blue-500">Facebook</span>
                    </a>
                    <a href="https://www.instagram.com" class="flex items-center space-x-2 group text-white no-underline">
                        <i class="fab fa-instagram text-xl md:text-2xl group-hover:text-pink-500"></i>
                        <span class="hidden md:inline-block group-hover:text-pink-500">Instagram</span>
                    </a>
                    <a href="https://tiktok.com" class="flex items-center space-x-2 group text-white no-underline">
                        <i class="fab fa-tiktok text-xl md:text-2xl group-hover:text-black"></i>
                        <span class="hidden md:inline-block group-hover:text-black">TikTok</span>
                    </a>
                    <a href="https://twitter.com" class="flex items-center space-x-2 group text-white no-underline">
                        <i class="fab fa-twitter text-xl md:text-2xl group-hover:text-blue-400"></i>
                        <span class="hidden md:inline-block group-hover:text-blue-400">Twitter</span>
                    </a>
                    <a href="mailto:youremail@gmail.com" class="flex items-center space-x-2 group text-white no-underline">
                        <i class="fas fa-envelope text-xl md:text-2xl group-hover:text-red-500"></i>
                        <span class="hidden md:inline-block group-hover:text-red-500">Gmail</span>
                    </a>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS
        <script src="js/scripts.js"></script>-->
        <script src="{% static 'js/scripts.js' %} "></script>
    </body>
</html>

panaderia_mana/templates/inicio_empleado.html
{% extends 'base.html' %}

{% block title %}
    Gestión del Sistema
{% endblock %}

{% block titulo %}
    Gestión del Sistema
{% endblock %}

{% block content %}
{% load static %}
    <div class="container mx-auto mt-5">

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-4">

            <!--hay que agregar los enlaces a cada pagina podria ser la de listar de cada uno-->


            <a href="{% url 'lista_productos' %}" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/productos.jpg' %}"  alt="Gestión de Productos" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Productos</h5>
            </a>
            <a href="{% url 'listar_empleados' %}" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/empleados.png' %}" alt="Gestión de Empleados" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Empleados</h5>
            </a>
            <a href="{% url 'listar_clientes' %}" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/clientes.jpeg' %}" alt="Gestión de Clientes" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Clientes</h5>
            </a>
            <a href="pedido/ " class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/pedidos.jpeg' %}" alt="Gestión de Pedidos" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Pedidos</h5>
            </a>
            <a href="{% url 'lista_insumos' %}" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/insumos.png' %}" alt="Gestión de Insumos" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Insumos</h5>
            </a>

            <a href="venta/lista_ventas" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/ventas.webp' %}" alt="Gestión de Ventas" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Ventas</h5>
            </a>
            <a href="pedido/ " class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/pedidos.jpeg' %}" alt="Gestión de Pedidos Recibidos" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Pedidos Recibidos</h5>
            </a>
            <a href="/proveedor/lista_proveedores" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/proveedores.jpeg' %}" alt="Gestión de Proveedores" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Proveedores</h5>
            </a>
            <a href="{% url 'pedido:lista_reportes' %}" class="link-image block bg-white rounded-lg shadow-lg overflow-hidden">
                <img src="{% static 'img/informes.jpg' %}" alt="Gestión de Informes" class="w-full h-48 object-cover">
                <h5 class="text-center p-2 font-semibold">Gestión de Informes</h5>
            </a>
        </div>
    </div>
{% endblock %}